//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Generated by 1337
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace NHTest.Model
{

    /// <summary>
    /// There are no comments for NHTest.Model.ProductLinkProducer, NHTest in the schema.
    /// </summary>
    public partial class ProductLinkProducer : BaseEntity {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          ProductLinkProducer toCompare = obj as ProductLinkProducer;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.LinkId, toCompare.LinkId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + LinkId.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for ProductLinkProducer constructor in the schema.
        /// </summary>
        public ProductLinkProducer()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for LinkId in the schema.
        /// </summary>
        public virtual long LinkId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public virtual Product Product
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Producer in the schema.
        /// </summary>
        public virtual Producer Producer
        {
            get;
            set;
        }
    }

}
